name: Run tests and style check

on:
  push:
    tags:
      - v*
  
  workflow_dispatch:

jobs:
  build-jar-job:
    name: 'Run Gradle build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 15'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
      - name: 'Build with Gradle'
        run: ./gradlew build
      - name: 'Release jar'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: Release ${{github.ref}}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: build/libs/*.jar
